# Generated by Django 4.2.17 on 2024-12-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_content_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
